hazelcast/management-center-docs

antora-playbook-local.yml
docs/antora.yml
docs/modules/ROOT/pages/configuring.adoc
docs/modules/ROOT/pages/getting-started.adoc
docs/modules/ROOT/pages/managing-licenses.adoc
docs/modules/ROOT/pages/metric-persistence.adoc
docs/modules/ROOT/pages/migration-guides.adoc
docs/modules/ROOT/pages/prometheus.adoc
docs/modules/ROOT/pages/user-interface.adoc
docs/modules/jmx/pages/appdynamics.adoc
docs/modules/jmx/pages/configuring.adoc
docs/modules/jmx/pages/new-relic.adoc
docs/modules/launching/pages/auth-options.adoc
docs/modules/launching/pages/launching.adoc
docs/modules/monitor-imdg/pages/client-filtering.adoc
docs/modules/monitor-imdg/pages/cluster-administration.adoc
docs/modules/monitor-imdg/pages/dashboard.adoc
docs/modules/monitor-imdg/pages/monitor-dds.adoc
docs/modules/monitor-jet/pages/jobs.adoc

- Fixed broken attributes (to get Asciidoctor.js to ignore anything in curly braces, you just add a backslash before the first brace `\{}` )
- Updated the `antora.yml` file so that the url includes `latest` as the version

Fix broken attributes

---

.github/workflows/build-site.yml
.github/workflows/build-staging.yml
.github/workflows/validate.yml
README.adoc

This PR also includes changes to the GitHub Action configurations so that the correct branches and tags trigger the workflows.

Add documentation for the new release process

---

docs/modules/monitor-imdg/pages/monitor-clients.adoc

Clarify what happens when a client is denied access to a cluster via
client filtering.

Improve client filtering docs

---

docs/modules/monitor-imdg/pages/monitor-clients.adoc

Bulleted list was not properly shown.

Cosmetic/formatting fix.

---

docs/modules/ROOT/pages/connecting-members.adoc

Related slack thread: https://hazelcast.slack.com/archives/C9S7BV74Z/p1623034245070300

documenting MC client connections when member security is enabled

---

docs/modules/ROOT/pages/config-healthcheck.adoc

Documenting this improvement: https://github.com/hazelcast/management-center/pull/4433

documenting periodic health check runner

---

docs/modules/ROOT/pages/connecting-members.adoc

Addressing the comments made by Serdaro in #52 (which was a backport of #50).

#50 follow-up: addressing PR comments

---

docs/modules/ROOT/pages/clustered-rest.adoc
docs/modules/jmx/pages/jmx-api.adoc

Required for https://github.com/hazelcast/management-center/pull/4432

Remove clusterType from clustered REST and JMX API docs

---

docs/modules/ROOT/pages/prometheus.adoc

related MC PR: https://github.com/hazelcast/management-center/pull/4515

MC-772 documenting prometheus basic auth

---

docs/modules/ROOT/pages/configuring.adoc

Follow-up of https://github.com/hazelcast/management-center/pull/4549

MC-897 documenting hazelcast.mc.hostAddress system property

---

docs/modules/jmx/pages/configuring.adoc

Logging info from MC 3.3 (2014) and have updated to what is shown in MC5.0

Update JMX logging

---

docs/modules/ROOT/pages/managing-clusters.adoc

Fixing content of example hazelcast-client.xml so that it parses successfully

---

docs/modules/ROOT/pages/managing-clusters.adoc

[BACKPORT] fixing content of example hazelcast-client.xml

---

docs/modules/deploy-manage/pages/active-directory.adoc
docs/modules/deploy-manage/pages/dev-mode.adoc
docs/modules/deploy-manage/pages/historical-metrics.adoc
docs/modules/deploy-manage/pages/jaas.adoc
docs/modules/deploy-manage/pages/ldap.adoc
docs/modules/deploy-manage/pages/local-security-provider.adoc
docs/modules/deploy-manage/pages/mc-conf.adoc
docs/modules/deploy-manage/pages/openid.adoc
docs/modules/deploy-manage/pages/saml.adoc
docs/modules/deploy-manage/pages/serve-mc-over-https.adoc
docs/modules/deploy-manage/pages/serving-https.adoc
docs/modules/deploy-manage/pages/sessions.adoc
docs/modules/deploy-manage/pages/system-properties.adoc
docs/modules/deploy-manage/pages/variable-replacers.adoc
docs/modules/getting-started/pages/install.adoc
docs/modules/getting-started/pages/overview.adoc
docs/modules/integrate/pages/clustered-rest.adoc
docs/modules/integrate/pages/jmx.adoc
docs/modules/integrate/pages/prometheus-monitoring.adoc
docs/modules/tools/pages/console.adoc
docs/modules/troubleshoot/pages/management-center.adoc

These changes were made in commit  #126 and had to be reapplied because we changed a lot of the structure in #135

Reapply MC-1107 changes in 89235eb

---

docs/modules/deploy-manage/pages/historical-metrics.adoc
docs/modules/deploy-manage/pages/system-properties.adoc
docs/modules/getting-started/pages/overview.adoc

- Updated documentation for [https://hazelcast.atlassian.net/jira/software/projects/MC/boards/46?selectedIssue=MC-1225](https://hazelcast.atlassian.net/jira/software/projects/MC/boards/46?selectedIssue=MC-1225)

Update docs for MC-1225

---

docs/modules/tools/pages/scripting.adoc

Scripting: update groovy dependency recommendation

---

docs/modules/deploy-manage/pages/system-properties.adoc
docs/modules/troubleshoot/pages/management-center.adoc

- updated docs for newly added env property

Update docs for MC-1285

---

docs/modules/data-structures/pages/map.adoc

https://hazelcast.slack.com/archives/C9S7BV74Z/p1646290109673419

Remove info about updating backup count

---

docs/modules/deploy-manage/pages/system-properties.adoc

fixing environment variable names

---

docs/modules/clusters/pages/update-config.adoc

Fix links to configuration

---

docs/modules/data-structures/pages/map.adoc

Provide examples of map events

---

docs/modules/deploy-manage/pages/active-directory.adoc
docs/modules/deploy-manage/pages/ldap.adoc
docs/modules/deploy-manage/pages/system-properties.adoc

- properties introduced in 5.2
- few missing metric storage properties
- LDAP SSL properties
- AD SSL properties

MС-1680 - system/env properties update for 5.2

---

antora-playbook-local.yml
antora-playbook.yml
docs/modules/release-notes/pages/5-1-3.adoc
docs/modules/release-notes/pages/5-1-4.adoc

Added {hazel-cloud} attribute to local playbooks
Added reference to mentions in release notes (so that future readers will be able to use/understand them)

DOCS-216 Replace HZ Cloud with HZ Viridian

---

docs/antora.yml
docs/modules/getting-started/pages/install.adoc

Related issue:  https://github.com/hazelcast/hz-docs/issues/557

Adding snapshot version to be used when installing with brew.

---

.github/workflows/backport-5.0.yml
.github/workflows/backport-5.1.yml
.github/workflows/backport-5.2.yml
docs/antora.yml

Fixes attributes issue identified in https://github.com/hazelcast/management-center-docs/pull/223#discussion_r1032506047.
Adds backport files for MC.

DOCS-320 Fix version attributes and add backport files

---

docs/antora.yml
docs/modules/getting-started/pages/get-started.adoc

Added new version attribute for Hazelcast in MC {hz-full-version}
Fixed typo

DOCS-311 Docker Compose Tutorial Minor amends

---

docs/modules/deploy-manage/pages/variable-replacers.adoc

Backport of https://github.com/hazelcast/management-center-docs/pull/240

MC-1881 Update command for EncryptionReplacer

---

docs/modules/monitor-streaming/pages/jobs.adoc

DOCS-384 Fix typo in streaming content

---

antora-playbook-local.yml
antora-playbook.yml

DOCS-549_API_Fix

---

antora-playbook-local.yml
antora-playbook.yml

Renaming Hazelcast Viridian to Viridian Cloud as per new branding.

DOCS-568 Product Renaming

---

docs/modules/deploy-manage/pages/sessions.adoc

Adds a note about the session timeout property's effectiveness.

Fixes #244

---

docs/modules/deploy-manage/pages/system-properties.adoc

Properties description mostly taken from Spring Boot CorsConfiguration class java docs. See  https://github.com/spring-projects/spring-framework/blob/4486ab1cb7d0ea915803b17251b2889c5a5320bc/spring-web/src/main/java/org/springframework/web/cors/CorsConfiguration.java

Add CORS configuration properties docs

---

docs/modules/clusters/pages/members.adoc

- Added new Device Usage data
- Rearranged the rows according to the current version

Update runtime table data in member details [MC-2549]

---

docs/modules/data-structures/pages/map.adoc

The screenshot will be updated in https://hazelcast.atlassian.net/browse/MC-2640

MC-2655 - update map config limitations

---

docs/modules/release-notes/pages/5-4-0.adoc
docs/modules/release-notes/partials/nav.adoc

5.4.0 - release notes

---

docs/modules/getting-started/pages/overview.adoc

fixes https://github.com/hazelcast/management-center-docs/issues/357

MC 5.5 is compatible with Platform 5.5

---

docs/modules/getting-started/pages/install.adoc

Backport of https://github.com/hazelcast/management-center-docs/pull/383

Add stop instructions [MC-2872] [5.5]

---

docs/antora.yml

Reverts hazelcast/management-center-docs#393

Revert "Update Version Variables on antora.yml  "

---

docs/antora.yml
docs/modules/getting-started/pages/install.adoc

See https://github.com/hazelcast/hz-docs/pull/1557

Remove `version-brew` property

---

.github/workflows/backport.yml

Support `5.7` backports

---

docs/modules/integrate/pages/prometheus-metrics.adoc

Copy of https://github.com/hazelcast/management-center-docs/pull/446 for main

Update metric name

---

docs/modules/clusters/pages/cluster-license.adoc
docs/modules/clusters/pages/members.adoc
docs/modules/deploy-manage/pages/updating-mc-license-ui.adoc

https://hazelcast.atlassian.net/browse/DOC-428

DOC-428 - remove references to tiered storage

---

package.json

Trying to fix Windows intsallation issue

Update ngrok version

---

docs/modules/integrate/pages/jmx.adoc

Addresses MC docs bug: Feedback for Clustered JMX #338

Update jmx.adoc with link to Datadog docs

---

docs/modules/integrate/pages/prometheus-metrics.adoc

Manual backport of https://github.com/hazelcast/management-center-docs/pull/516

[EMGR-438] Define V1 and V2 Metrics

---

docs/modules/integrate/pages/prometheus-metrics.adoc

Backport https://github.com/hazelcast/management-center-docs/pull/519

Copy edit Prometheus metrics doc - 5.7

---

docs/modules/deploy-manage/pages/production-checklist.adoc

Added note to fix doc bug: https://github.com/hazelcast/management-center-docs/issues/427

DOC-443-bug: add note to fix doc bug

---

docs/modules/release-notes/pages/releases.adoc

Add releases overview

---

docs/modules/clusters/pages/shutting-down-cluster.adoc
docs/modules/clusters/pages/wan-replication.adoc
docs/modules/cp-subsystem/pages/dashboard.adoc
docs/modules/getting-started/pages/install.adoc
docs/modules/troubleshoot/pages/hazelcast-clusters.adoc
docs/modules/troubleshoot/pages/management-center.adoc

Mopping up the removal of some remaining gerunds

DOC-483-tidy: remove gerunds

---

antora-playbook.yml
docs/antora.yml

relates to https://github.com/hazelcast/management-center/pull/11012

Convert 6.0.0-SNAPSHOT into 5.9.0-SNAPSHOT

---

docs/modules/getting-started/pages/install.adoc

Reverts hazelcast/management-center-docs#586 for easy backporting

Revert "Revert "Fix the links for downloading the latest snapshot""

---

docs/modules/getting-started/pages/install.adoc

Reverts hazelcast/management-center-docs#585

Revert "Fix the links for downloading the latest snapshot"

---

docs/modules/getting-started/pages/install.adoc

Revert "Revert "Fix the links for downloading the latest snapshot"" [v/5.2]

---

docs/modules/getting-started/pages/install.adoc

Revert "Revert "Fix the links for downloading the latest snapshot"" [v/5.4]

---

docs/modules/getting-started/pages/install.adoc

Revert "Revert "Fix the links for downloading the latest snapshot"" [v/5.5]

---

docs/modules/getting-started/pages/install.adoc

Revert "Revert "Fix the links for downloading the latest snapshot"" [v/5.6]

---

docs/modules/getting-started/pages/install.adoc

Revert "Revert "Fix the links for downloading the latest snapshot"" [v/5.7]

---

antora-playbook.yml
docs/modules/ROOT/nav.adoc
docs/modules/integrate/pages/clustered-rest.adoc
docs/modules/integrate/pages/diagnostics-config.adoc
docs/modules/integrate/partials/nav.adoc

https://github.com/hazelcast/management-center/pull/11167

[MC-3322] Expose diagnostics-config Open API docs
