README.adoc
antora-playbook-local.yml
docs/antora.yml

Updated GitHub links so that they don't break when we transfer ownerhip of this repository to the hazelcast organization

Update links to hazelcast repo

---

docs/modules/ROOT/pages/prometheus.adoc

The PR implementing the feature is: https://github.com/hazelcast/management-center/pull/4202

Documenting how to run the Prometheus exporter on a custom port

---

antora-playbook-local.yml
docs/modules/ROOT/pages/connecting-members.adoc
docs/modules/ROOT/pages/getting-started.adoc
docs/modules/monitor-imdg/pages/cluster-administration.adoc
docs/modules/monitor-imdg/pages/dashboard.adoc
docs/modules/monitor-imdg/pages/monitor-clients.adoc
docs/modules/monitor-imdg/pages/monitor-dds.adoc
docs/modules/monitor-imdg/pages/monitor-wan-replication.adoc
package.json

Hi, I'm from MC team, a front-end developer.
While fixing broken IMDG docs links we discovered that some links in the docs are also broken (e.g. pointing to wrong sections).
This PR changes the remaining "raw" links to use cross-reference instead. 
Is there anything else that needs to be done?

Fix: use xref for IMDG links

---

.github/workflows/build-site.yml
.github/workflows/build-staging.yml
.github/workflows/validate.yml
README.adoc

This project does not use `.z` branches because it does not support older versions.
Instead it branches from `main` for each release.

Fix typos and remove references to .z branch

---

src/docs/asciidoc/mc_conf_tool.adoc

We have a new mc-conf command named configure-time-travel, added in https://github.com/hazelcast/management-center/pull/4248.

Add documentation for a new mc-conf command

---

.brok-ignore-links
.github/workflows/build-site.yml
.github/workflows/validate.yml
README.adoc
antora-playbook-local.yml
antora-playbook.yml
check-links-playbook.yml

This PR addresses the issues that make it difficult to backport changes.
Updated the release workflow:
- To use branches instead of tags.

Update release workflow

---

docs/modules/monitor-streaming/pages/dashboard.adoc

The referred contents are identical.

MC-890 replacing jet-start links with docs.hazelcast.com links

---

docs/antora.yml

Otherwise 5.0 is rendered as 5, which breaks links

Wrap versions in single quotes

---

docs/modules/monitor-imdg/pages/cluster-administration.adoc

CP subsystem is supported by Hazelcast clusters 3.12+. Since MC5+ can't connect to pre 3.12 clusters we don't need NOT_SUPPORTED status anymore

MC-895- remove 'CP sybsystem not supported' status

---

docs/modules/clusters/pages/client-filtering.adoc

We missed a redirect in #135. This PR redirects `/monitor-imdg/client-filtering` to the new location.

Add redirect

---

README.adoc

Updated the release workflow for Platform.
We now track the latest support version of Management Center in the Platform docs as well, so this workflow explains the steps needed for snapshot, latest, and patch releases of MC.

Update the release workflow

---

docs/modules/clusters/pages/clients.adoc
docs/modules/deploy-manage/pages/connecting-to-clusters-ui.adoc

- update docs to state that MC-Clients are not included while displaying client counts on the left menu and cluster connections screen 
- https://github.com/hazelcast/management-center/pull/5379

update docs for MC-1162

---

docs/modules/deploy-manage/pages/user-management.adoc

The "user" role's "Member Shutdown" will be accordingly edited for 5.2, 5.1, and 5.0 versions.

Adding detailed info on user roles [DOCS-361]

---

docs/modules/getting-started/pages/overview.adoc

- Internet Explorer 11 is no longer supported. Updated the docs to state that.

MC-1871 Drop official support for IE11 - Docs

---

docs/modules/data-structures/pages/map.adoc

- Some map browser fields didn't get as expected in MC.
- It is because the map's `per-entry-stats` config is disabled by default.
- Added a warning to the MC to state that cause and added a link to the MC docs.
- Added an explanation in MC docs and link to the Hazelcast docs.

MC-1671 Incorrect information on map browser -[docs]

---

antora-playbook.yml

Update snapshot version to current version.
This may not work, as may only support 5.x rather than 5.x.x

DOCS-549 Update snapshot version

---

antora-playbook.yml
docs/modules/deploy-manage/pages/system-properties.adoc
docs/modules/integrate/pages/prometheus-monitoring.adoc

- Management Center collects metrics with the timestamp of the individual members and send this timestamp to Prometheus each time. 
- Prometheus discards metrics with old timestamps. 
- We need to disable sending this timestamp to Prometheus so that user's monitoring system continues to operate when clock shifts happen in the cluster.

MC-2127 Prometheus metrics - make timestamp optional

---

docs/modules/getting-started/pages/overview.adoc

Minor corrections - pluralize "example", missing period.

Update overview.adoc - small typos

---

docs/modules/data-structures/pages/map.adoc
docs/modules/data-structures/pages/replicated-map.adoc

As requested by https://hazelcast.atlassian.net/browse/SUP-361

Fixes SUP-361

---

.github/workflows/action-updater.yml
.github/workflows/backport-5.0.yml
.github/workflows/backport-5.1.yml
.github/workflows/backport-5.2.yml
.github/workflows/backport-5.3.yml
.github/workflows/backport-to-beta.yml
.github/workflows/validate.yml

* **[shioyang/check-pr-labels-on-push-action](https://github.com/shioyang/check-pr-labels-on-push-action)** published a new release **[v1.0.9](https://github.com/shioyang/check-pr-labels-on-push-action/releases/tag/v1.0.9)** on 2023-01-07T05:09:53Z
* **[actions/setup-node](https://github.com/actions/setup-node)** published a new release **[v4.0.2](https://github.com/actions/setup-node/releases/tag/v4.0.2)** on 2024-02-07T04:51:19Z
* **[actions/checkout](https://github.com/actions/checkout)** published a new release **[v4.1.1](https://github.com/actions/checkout/releases/tag/v4.1.1)** on 2023-10-17T15:53:17Z

Updated action versions

---

README.adoc

Currently links to a [deprecated repository](https://github.com/hazelcast/hazelcast-reference-manual?tab=readme-ov-file#deprecated-this-repository-has-been-deprecated-please-continue-to-httpsgithubcomhazelcastimdg-docs), when should link to this repository.

Ensure `README`'s `Contributing` section links to the right repository

---

docs/modules/getting-started/pages/overview.adoc

Update support channels in documentation:
- Google Group link removed
- > The Hazelcast Google User Group is read-only. Please post your questions on the Hazelcast Community Slack)
- Slack link reworded
- Hazelcast does not guarantee development team support

Update documentation support links

---

docs/modules/getting-started/pages/overview.adoc

I believe the latest released versions of Hazelcast and Management Center are compatible.

MC `5.5` does not list compatibility with HZ `5.5`

---

check-links-playbook.yml
docs/antora.yml

There is no 5.5.0 branch in hz-docs repo. The correct branch name is 5.5
Probably it is causing a bunch of errors during build 
https://app.netlify.com/sites/nifty-wozniak-71a44b/deploys/66d57f135ffe120008c408d8#L637

Fix latest supported platform version

---

docs/antora.yml

[The dead links checks in `hz-docs` are failing](https://github.com/hazelcast/hz-docs/actions/workflows/validate.yml).
_One_ of the reasons for this is that the action checks out the default branch for all repos, builds the documentation and checks for linkage errors.
The problem is that `hz-docs` is building `6.0-snapshot` docs, but the `management-center-docs` links are to `5.5.0`, which doesn't exist locally in this configuration.
I believe this is why when `hz-docs`'s version was upgraded, so was [`management-center-docs`, too](https://github.com/hazelcast/management-center-docs/commit/36aa40a611cae82a2442dfc2c48fdcecb4401807).
This was subsequently reverted in https://github.com/hazelcast/management-center-docs/pull/355, which _I don't believe_ was intentional.
_Partially fixes_: …

Revert `page-latest-supported-hazelcast` to `6.0-snapshot` [DOC-125]

---

docs/antora.yml

Required to support updating [`latest-supported-mc` in `clc-docs`](https://github.com/hazelcast/clc-docs/blob/e2c20ca40fc13d38f09b6bba761a9fcacd2bfe2d/docs/antora.yml#L20), in https://github.com/hazelcast/management-center/pull/9786
Post-merge action:

Add `page-latest-supported-clc`

---

docs/modules/launching/pages/auth-options.adoc

Fixes
```
3:58:10 PM: [12:58:10.281] WARN (asciidoctor): skipping reference to missing attribute: 0
3:58:10 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:10 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2021.04 | start path: docs)
3:58:10 PM: [12:58:10.282] WARN (asciidoctor): skipping reference to missing attribute: 1
3:58:10 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:10 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2021.04 | start path: docs)
3:58:10 PM: [12:58:10.282] WARN (asciidoctor): skipping reference to missing attribute: 0
3:58:10 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:10 PM:     source: https://github.com/hazelcast/management-center-docs …
```

Fix build warnings v/4.2021.04

---

docs/modules/launching/pages/auth-options.adoc

Fixes
```
3:58:12 PM: [12:58:12.915] WARN (asciidoctor): skipping reference to missing attribute: 0
3:58:12 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:12 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2021.12-1 | start path: docs)
3:58:12 PM: [12:58:12.915] WARN (asciidoctor): skipping reference to missing attribute: 1
3:58:12 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:12 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2021.12-1 | start path: docs)
3:58:12 PM: [12:58:12.916] WARN (asciidoctor): skipping reference to missing attribute: 0
3:58:12 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:12 PM:     source: …
```

Fixes build warnings v/4.2021.12 1

---

docs/modules/launching/pages/auth-options.adoc

Fixes
```
3:58:13 PM: [12:58:13.783] WARN (asciidoctor): skipping reference to missing attribute: 0
3:58:13 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:13 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2022.01 | start path: docs)
3:58:13 PM: [12:58:13.783] WARN (asciidoctor): skipping reference to missing attribute: 1
3:58:13 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:13 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2022.01 | start path: docs)
3:58:13 PM: [12:58:13.783] WARN (asciidoctor): skipping reference to missing attribute: 0
3:58:13 PM:     file: docs/modules/launching/pages/auth-options.adoc
3:58:13 PM:     source: https://github.com/hazelcast/management-center-docs …
```

Fix build warnings v/4.2022.01

---

docs/modules/deploy-manage/pages/system-properties.adoc

Fixes
```
3:58:19 PM: [12:58:19.191] WARN (asciidoctor): id assigned to anchor already in use: hazelcast-mc-ldap-ssl-truststorepassword
3:58:19 PM:     file: docs/modules/deploy-manage/pages/system-properties.adoc:584
3:58:19 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/5.2 | start path: docs)
```
https://app.netlify.com/sites/nifty-wozniak-71a44b/deploys/66e97ba4dd50b60008d9236e#L237

Fix build warnings v/5.2

---

docs/modules/deploy-manage/pages/system-properties.adoc

Fixes
```
3:58:21 PM: [12:58:21.220] WARN (asciidoctor): id assigned to anchor already in use: hazelcast-mc-ldap-ssl-truststorepassword
3:58:21 PM:     file: docs/modules/deploy-manage/pages/system-properties.adoc:584
3:58:21 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/5.3 | start path: docs)
```

Fix build warnings v/5.3

---

docs/modules/deploy-manage/pages/h2-upgrade.adoc
docs/modules/deploy-manage/pages/system-properties.adoc

```
3:58:25 PM: [12:58:25.163] WARN (asciidoctor): skipping reference to missing attribute: mc_home
3:58:25 PM:     file: docs/modules/deploy-manage/pages/h2-upgrade.adoc
3:58:25 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/5.5 | start path: docs)
3:58:25 PM: [12:58:25.163] WARN (asciidoctor): skipping reference to missing attribute: mc_home
3:58:25 PM:     file: docs/modules/deploy-manage/pages/h2-upgrade.adoc
3:58:25 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/5.5 | start path: docs)
3:58:25 PM: [12:58:25.163] WARN (asciidoctor): skipping reference to missing attribute: timestamp
3:58:25 PM:     file: docs/modules/deploy-manage/pages/h2-upgrade.adoc
3:58:25 PM:     source: …
```

Fix build warnings v/5.5

---

.github/workflows/action-updater.yml
.github/workflows/backport-5.0.yml
.github/workflows/backport-5.1.yml
.github/workflows/backport-5.2.yml
.github/workflows/backport-5.3.yml
.github/workflows/backport-5.4.yml
.github/workflows/backport-5.5.yml
.github/workflows/backport-to-beta.yml
.github/workflows/validate.yml

Following on from https://github.com/hazelcast/hz-docs/pull/1316, all GitHub actions should use the latest `v4` rather than some hardcoded sub-version.

Use latest `v4` of GitHub Actions

---

docs/modules/launching/pages/auth-options.adoc

Fixes
```
4:41:20 PM: [13:41:20.811] WARN (asciidoctor): skipping reference to missing attribute: 0
4:41:20 PM:     file: docs/modules/launching/pages/auth-options.adoc
4:41:20 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2021.12 | start path: docs)
4:41:20 PM: [13:41:20.813] WARN (asciidoctor): skipping reference to missing attribute: 1
4:41:20 PM:     file: docs/modules/launching/pages/auth-options.adoc
4:41:20 PM:     source: https://github.com/hazelcast/management-center-docs (branch: v/4.2021.12 | start path: docs)
4:41:20 PM: [13:41:20.813] WARN (asciidoctor): skipping reference to missing attribute: 0
4:41:20 PM:     file: docs/modules/launching/pages/auth-options.adoc
4:41:20 PM:     source: https://github.com/hazelcast/management-center-docs …
```

Fix warnings

---

.github/workflows/backport-5.5.yml

Syntax error causing [execution failure](https://github.com/hazelcast/management-center-docs/actions/runs/11289108705):
> The workflow is not valid. .github/workflows/backport-5.5.yml (Line: 1, Col: 1): Unexpected value 'cname'

Fix `backport-5.5.yml`

---

docs/antora.yml

In https://github.com/hazelcast/management-center-docs/pull/360, `page-latest-supported-hazelcast` was incorrectly incremented.
Although Hazelcast's `main` branches had upgraded to `v6`, Management Center's `main` branch was still targeting `v5` with new releases - meaning `v5.6` docs' URLs are pointing at `6.0.0-SNAPSHOT` documentation.
Now that [`management-center-docs` is `v6`](https://github.com/hazelcast/management-center-docs/commit/adec11cd84dff1c0dabd541ef6afccccb1a38efb), this is no longer an issue on `main`, and can simply be reverted on a maintenance branch.
[Slack discussion](https://hazelcast.slack.com/archives/C035HQET5/p1732814748534219).

Set `page-latest-supported-hazelcast` correctly in `v/5.6'

---

.github/workflows/build-site.yml

Based on our [runner selection documentation](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/5358485538/GitHub+Runner+Selection+Guide), we should be using the GitHub runners for actions executed in public repos as they are free vs using paid-for `ubicloud` minutes.

Use GitHub runners as public repo

---

docs/modules/deploy-manage/pages/system-properties.adoc
docs/modules/integrate/pages/prometheus-metrics.adoc
docs/modules/integrate/pages/prometheus-monitoring.adoc
docs/modules/integrate/partials/nav.adoc

https://hazelcast.atlassian.net/browse/MC-3171
Related platform docs changes: https://github.com/hazelcast/hz-docs/pull/1508

DOC-353 Prometheus metrics standardization

---

docs/modules/integrate/pages/prometheus-metrics.adoc

Fixing updated value for map_index_totalInsertLatency. It should be map_index_latency_total_seconds. (ref. SF case: 14639)

Fixing updated metric name in Prometheus metrics

---

docs/antora.yml

We should not be referencing a `SNAPSHOT` version in production docs.

Remove Hazelcast `SNAPSHOT` reference from production docs

---

docs/modules/getting-started/pages/get-started.adoc

Addresses warning:
```
attribute `version` is obsolete
```
https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-top-level-element-obsolete

Remove Docker compose obselete `version` attribute

---

docs/antora.yml
docs/modules/getting-started/pages/get-started.adoc

MC docs contain a reference to Hazelcast platform version, but this has some issues:
- it's _sometimes_ manually updated but not part of a checklist to ensure it always is
- it's outdated
- EE and OS versions are different so a single Hazelcast version doesn't make sense
- It's been set to an EE version but it's being _used_ like an OS version - the `hazelcast/hazelcast:5.5.2` Docker image does not exist
[MC is backwards compatible with older Hazelcast versions](https://hazelcast.slack.com/archives/C9S7BV74Z/p1738850869425519) - I assume the inverse is true, so in that case `latest` seems the most sensible and easiest to maintain.
Whether we should backport this change is up for discussion - it won't backport "cleanly" due to conflicts and no-one has reported this as an issue.

Remove `hz-full-version` property

---

docs/antora.yml

The CLC version in the docs is outdated.
Note this step is listed in the [CLC release process](https://hazelcast.atlassian.net/wiki/spaces/HZC/pages/3731193857/Commandline+Client+Releases).
Unsure version compatibility ranges to determine appropriate backport.

Updated outdated CLC version

---

docs/modules/integrate/pages/prometheus-metrics.adoc

There's no definition of `V1` and `V2` metrics, only `original` and `updated` which leaves the reader to determine which is `V1` and which is `V2`. `V1` and `V2` are defined in this PR as these are the values that can be configured in the property: `hazelcast.mc.prometheusExporter.printers`.

[EMGR-438] Define V1 and V2 Metrics and their Differences

---

docs/modules/getting-started/pages/install.adoc

The syntax is incorrect, should match the format specified in `management-center-packaging`: https://github.com/hazelcast/management-center-packaging/blob/a18ccab300059bc0ba1a067f28e53d513a6d8063/README.md?plain=1#L99
Fixes https://github.com/hazelcast/management-center-docs/issues/538

Fix RPM installation command

---

docs/modules/getting-started/pages/get-started.adoc

The compose section was set as "bash" instead of "yaml"

Licensing typo fix

---

docs/modules/deploy-manage/pages/variable-replacers.adoc

Correcting fully qualified name of the PropertiesLauncher class

---

docs/modules/deploy-manage/pages/variable-replacers.adoc

Backport of https://github.com/hazelcast/management-center-docs/pull/535

Correcting fully qualified name of the PropertiesLauncher class [v/5.4]

---

docs/modules/deploy-manage/pages/variable-replacers.adoc

Backport of https://github.com/hazelcast/management-center-docs/pull/535

Correcting fully qualified name of the PropertiesLauncher class [v/5.5]

---

docs/modules/deploy-manage/pages/variable-replacers.adoc

Backport of https://github.com/hazelcast/management-center-docs/pull/535

Correcting fully qualified name of the PropertiesLauncher class [v/5.7]

---

docs/modules/deploy-manage/pages/variable-replacers.adoc

Backport of https://github.com/hazelcast/management-center-docs/pull/535

Correcting fully qualified name of the PropertiesLauncher class [v/5.8]
